### ISSUE TITLE
How to connect a battery?

### ISSUE THREAD

**Issue by pfefferCode** [SonnenladenGmbH/APsystems-EZ1-API-HomeAssistant#13]
Hi!

I think, controlling the output power of the inverter makes sense only if you have a battary - otherwise controlling it down is just wasted energy (which could be used by someone else on the grid).

So: How do you connect a storage battery? (And do you have a recommendation for which one to use?)

Thanx!
  PfefferCode.

**Comment by mawoka-myblock** [comment]
I think that we won't be able to help you regarding this question, as I am just familiar with software. To your point of the "useless" option to limit output: I don't think that's useless. You can for example, turn it down so you don't exceed your legal limit or you could prevent energy from exiting your home network, when that's required. And, tbh, if the inverter has the option to do that, why disable it when there's only a very limited use-case?

But sorry, I really can't help you with your main question. I'd recommend asking in a dedicated solar forum or something.

Some detail I can give you is the following: As far as I know, you can just feed 24v or so into one of the solar connections which the inverter will happily accept. But I won't be responsible for a dead inverter ;)
