### ISSUE TITLE
Unable to prepare setup for platform apsystemsapi_local.sensor: Platform not found

### ISSUE THREAD

**Issue by Nelson666** [SonnenladenGmbH/APsystems-EZ1-API-HomeAssistant#15]
The HACS installation (2.0.1) are ok, but I have this error after a restart from HA. 
Note: This is my first installation of this plugin. 

```
Logger: homeassistant.setup
Source: setup.py:379
First occurred: 14:29:28 (3 occurrences)
Last logged: 14:29:28

Unable to prepare setup for platform apsystemsapi_local.sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
Unable to prepare setup for platform apsystemsapi_local.number: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
Unable to prepare setup for platform apsystemsapi_local.switch: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
```

**Comment by mawoka-myblock** [comment]
Could you please tell me your HomeAssistant version?

**Comment by Nelson666** [comment]
Sure, here are the versions. 

`Home Assistant 2023.8.3
Frontend 20230802.1 - latest `

**Comment by mawoka-myblock** [comment]
Unfortunately I can't provide support for such an outdated version of Home Assistant. Please update HA and tell MSF of the issue persists.

**Comment by Nelson666** [comment]
Ok, i update my HA installation and we will see. 

Thank you

**Comment by hmueller01** [comment]
I have to use Home Assistant 2023.7.3 on my Synology nas, as 
https://github.com/hgy59/spksrc/tree/master/spk/homeassistant/src
doesn't support a newer version.

But if you replace 
```
-from homeassistant.helpers.device_registry import DeviceInfo
+from homeassistant.helpers.entity import DeviceInfo
```
in `sensor.py, switch.py, number.py` it works.

**Comment by mawoka-myblock** [comment]
Keeping backwards compatibility isn't something I want to do, as the HA ecosystem seems to not care for that as well.

**Comment by mawoka-myblock** [comment]
No problem, also thank you for providing the solution!
