### ISSUE TITLE
Use of input.number for max Power

### ISSUE THREAD

**Issue by HABen91** [SonnenladenGmbH/APsystems-EZ1-API-HomeAssistant#22]
Is it possible to Switch the max Power setting from beeing a "number" to an "Input.number"?
This would allow to use a standard Automation to increase/decrease the value by increments. Doing this allows to realize a zero return  regulation to optimize power usage when using a Powerbank.

**Comment by mawoka-myblock** [comment]
As far as I am aware, HA doesn't differentiate between these types. Could you please link some docs regarding that?

**Comment by HABen91** [comment]
Hey,Here are some links to HA Dokumentation:https://www.home-assistant.io/integrations/number/https://www.home-assistant.io/integrations/input_number/In the attached Screenshot you will find the offered options to manipulate the different "kinds" of Numbers.Am 26.03.2024 21:50 schrieb Marlon ***@***.***>:
As far as I am aware, HA doesn't differentiate between these types. Could you please link some docs regarding that?

**Comment by mawoka-myblock** [comment]
That's not how it works.
Here's a screenshot showing you how to achieve your goal:
![Screenshot_20240326-221903_Home Assistant](https://github.com/SonnenladenGmbH/APsystems-EZ1-API-HomeAssistant/assets/66328166/ac8c8665-fe95-4ee9-ba46-1475a598bc7f)

**Comment by HABen91** [comment]
The issue hast not been understood. The offered solution allows only fixed values but not incremantally reacting on other criteria.

**Comment by mawoka-myblock** [comment]
Incrementing in watt-steps won't make sense as the inverter takes 1-2 seconds. Additionally, you seem to confuse the way HA integrations are built in contrast to helper integrations.
There are 3 solutions:
1. Use spook: https://spook.boo/number
2. Use templates to increment the value
3. Somebody spends time adding a custom service to this integration for this exact purpose and I won't be spending that time as I personally wouldn't benefit from that.
