### ISSUE TITLE
device_class `energy` for sensor.power

### ISSUE THREAD

**Issue by JM-Lemmi** [SonnenladenGmbH/APsystems-EZ1-API-HomeAssistant#44]
To use the `power_p1`, `power_p2` and `total_power` sensors in the energy dashboard, they need to have a `device_class` of `energy`.

Currently the `device_class` is `power`.

I propose changing the class to `energy`.

**Comment by mawoka-myblock** [comment]
That's not how it work, as Watt is a unit of power, not of energy, which is also documented int the [HA docs](https://developers.home-assistant.io/docs/core/entity/sensor#available-device-classes)
